name: CI/CD for Next.js App

on:
  push:
    branches:
      - develop

env:
  PROJECT_NAME: nextjs-app

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    # needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup SHA
        run: echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/develop' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.GITHUB_SHA }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  gitops-versioning:
    runs-on: ubuntu-22.04
    needs: [build-and-push-docker-image]
    name: GitOps Versioning
    steps:
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y yq
      - name: change image tag to deploy dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/ZFlucKZ/nonprod-k8s-manifest-2.git

          cd nonprod-k8s-manifest-2/dev/nextjs-app

          git config user.name "robot"
          git config user.email "robot@pajj.com"

          yq --version
          yq e '.spec.template.spec.containers[0].image = "${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${GITHUB_SHA}"' -i deployment.yaml

          git add deployment.yaml
          git commit -m "[skip actions] 🤖 change develop docker image version ${GITHUB_SHA}"
          git push origin main

# 19fd1193e08d8bfc0f4e0e16e3b8833da3cae866
